# Generated by Django 5.2.1 on 2025-12-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('director', 'Director'), ('visitor', 'Visitor'), ('trainer', 'Trainer'), ('worker', 'Worker'), ('maintenance', 'Maintenance')], max_length=50, unique=True),
        ),
    ]
