# Generated by Django 5.2.1 on 2025-12-16 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsapp', '0009_alter_shift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('director', 'Director'), ('visitor', 'Visitor'), ('member', 'Member'), ('trainer', 'Trainer'), ('worker', 'Worker'), ('maintenance', 'Maintenance'), ('receptionist', 'Receptionist')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gmsapp.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
