# Generated by Django 5.2.1 on 2025-12-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsapp', '0012_inquirystatus_receptionist_telegram_chat_id_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
